### ISSUE TITLE
LHAPDF issue

### ISSUE THREAD

**Issue by scarlehoff** [Zaharid/conda-recipes#1]
The current LHAPDF package in conda produces the following error:

```
    ag = ap.add_add_mutually_exclusive_group()
AttributeError: 'ArgumentParser' object has no attribute 'add_add_mutually_exclusive_group'
```
How to reproduce:

`lhapdf list`

The cause is because the lhapdf.py file in the official source has that extra add (it should be `ag = ap.add_mutually_exclusive_group()`).

The solution is to patch it at build time. Not sure for how long has it been there since I don't use conda @Radonirinaunimi found it this morning. I can have a go a it tomorrow but I'm no expert in coda recipes so it might take me more time than it is worth it.

**Comment by Zaharid** [comment]
I am confused: which is the official source and how does it differ from

https://github.com/Zaharid/conda-recipes/blob/1d090c2a8e467501ba50fcfdd89fbb716ba697d3/0-lhapdf/meta.yaml#L2

?

**Comment by scarlehoff** [comment]
By official I mean the one you download from the webpage (and the one you are using). The bug is part of the release.
Maybe it is a feature :P

**Comment by Zaharid** [comment]
Sorry, I had misread and deleted the previous comment. Will fix. Please do report to the authors as well.

**Comment by Zaharid** [comment]
Actually this is fixed in the head of the mercurial repo for LHAPDF (together with a bunch of other things). Maybe it is easier to ask @agbuckley for a release than to maintain patches in here?

**Comment by scarlehoff** [comment]
It would be the best, yes. I'm surprised it has gone unnoticed for so long, I think 6.2.3 has been out for a while. Do you know whether @agbuckley is in git or should I send him an email?

**Comment by agbuckley** [comment]
Hi, yes I am on here. 6.2.3 has not been out *that* long, but there are a few known bugs like this (which were patched in the LCG installations). There are quite a few other developments in the pipeline, but time has been very short and LHAPDF is supported on a "best effort" basis, hence no release yet. Thanks for including me: this bumps it up the mental to-do list a little ;-)

**Comment by Zaharid** [comment]
Note that at the moment it is possible to edit the file that gets installed in the conda environment. Not great but should do the trick for a while.

**Comment by scarlehoff** [comment]
Yes, that's what we did. I was just surprised nobody else noticed, but I guess most of the time LHAPDF is accessed from validphys.

**Comment by Zaharid** [comment]
Yeah, I rarely care about the PDFs I have installed because they get downloaded automatically :)

**Comment by Zaharid** [comment]
There is now a new version of LHAPDF which should fix this.
