### ISSUE TITLE
Move `lhapdf` to conda-forge

### ISSUE THREAD

**Issue by scarlehoff** [Zaharid/conda-recipes#5]
It should be perfectly fine to move the recipe there https://gitlab.com/hepcedar/lhapdf/-/blob/main/COPYING

And would allow us to create the packages for `eko` (and `nnpdf` as soon as we drop `apfel`) directly in `conda-forge`. I'll do that next week, do you want to be added as a maintainer to the `conda-forge` entry?

**Comment by Zaharid** [comment]
Sure.

**Comment by Zaharid** [comment]
Here you are https://github.com/conda-forge/staged-recipes/pull/18315

**Comment by scarlehoff** [comment]
You might need to ping one of the groups to get the recipe reviewed

```
Currently available teams are:
- python `@conda-forge/help-python`
- python/c hybrid `@conda-forge/help-python-c`
- r `@conda-forge/help-r`
- java `@conda-forge/help-java`
- nodejs `@conda-forge/help-nodejs`
- c/c++ `@conda-forge/help-c-cpp`
- perl `@conda-forge/help-perl`
- Julia `@conda-forge/help-julia`
- ruby `@conda-forge/help-ruby`
```
